Repository nss-day-cohort-46/rare-client-elusive-elves, pull requests merged in 2021-04, with the labels that each got.

#2 Cc usehistory hook
  package-lock.json
  src/components/auth/Register.js
Labels: documentation

#7 feat: Correctly displays author name in post details
  src/components/ApplicationViews.js
  src/components/posts/PostCard.js
  src/components/posts/PostDetails.js
  src/components/posts/PostForm.js
  src/components/posts/PostList.js
Labels: documentation

#10 Nah categories
  src/components/ApplicationViews.js
  src/components/category/CategoryCard.js
  src/components/category/CategoryForm.js
  src/components/category/CategoryList.js
  src/components/nav/NavBar.js
Labels: documentation

#16 Nah manage categories
  src/components/ApplicationViews.js
  src/components/category/CategoryCard.js
  src/components/category/CategoryDetails.js
  src/components/category/CategoryForm.js
Labels: documentation

#19 fix: update form control
  src/components/category/CategoryForm.js
Labels: documentation

#23 Nah delete modal
  src/components/category/CategoryDetails.js
Labels: documentation

#22 Nah cancel option
  src/components/category/CategoryDetails.js
  src/components/category/CategoryForm.js
  src/components/category/CategoryList.js
Labels: enhancement

#24 fix: deleteCategory modal
  src/components/category/CategoryDetails.js
Labels: documentation

#27 Cc tags by posts
  src/components/ApplicationViews.js
  src/components/nav/NavBar.js
  src/components/tags/Tag.js
  src/components/tags/TagDetail.js
  src/components/tags/TagForm.js
  src/components/tags/TagList.js
  src/components/tags/TagsProvider.js
Labels: documentation, enhancement

#28 Confirm delete for comments & posts
  src/components/category/CategoryProvider.js
  src/components/comments/CommentCard.js
  src/components/comments/CommentDetails.js
  src/components/comments/CommentForm.js
  src/components/posts/PostDetails.js
Labels: documentation

#30 Cj subscriptions
  src/components/category/CategoryForm.js
  src/components/comments/CommentList.js
  src/components/posts/PostDetails.js
Labels: enhancement
